
general:
  save_dir: "./pretrained_models/"
  device: "cuda"
  seed: 30
  num_workers: 0
  log_dir: "pd_logs"
  progress_bar: True
  n_samples_each_class: 100
  max_images: null
  callback_every: 1
  callback_digits: False
  sweeping_stepsize: 1
  show_probs: False

dataset:
  dataset: "pd"
  include_classes: [0,1]

classifier:
  classifier: "linClassifier"
  model_name: "pd"
  epochs: 50
  batch_size: 32
  lr: 0.1
  b1: 0.5
  b2: 0.999
  weight_decay: 0.01
  optimizer: "Adam"
  no_print: True
  n_features: 184

vae:
  vae_model: "vanilla_Encoder"
  model_name: "pd"
  use_causal: True
  n_alpha: 1
  n_beta: 7
  alpha_samples: 100
  beta_samples: 25
  lam_ml: 0.05
  batch_size: 4096
  lr: 0.0005
  b1: 0.5
  b2: 0.999
  weight_decay: 0.01
  optimizer: "Adam"
  n_features: 21
  epochs: 30
